### ISSUE TITLE
[Third delivery] Summary - Sebas contribution

### ISSUE THREAD

**Issue by sebaslh01** [Arquisoft/dede_en1b#107]
In this delivery, I was in charge of doing the testing of product list view and product details views, improvements of these both views and creating of the rating functionality along with Daniel.

I could not do the testing part, as I encountered some problems with the change of state of the components and I run out of time.

I started working with @danieladov  in the branch [Review](https://github.com/Arquisoft/dede_en1b/tree/Review). It's only missing the front part for adding a review. 

I added the carousel of images in product details view, closing:
-  #69 

And I reviewed the following Pull Requests: 

-  #103 

-  #104

**Comment by pglez82** [comment]
Hi Sebas,

I need for you to add the links to the PR where you did the tests. If they are not merged yet, at least the link to the branch where you did that work for this release.

Pablo

**Comment by sebaslh01** [comment]
Okay but... I didn't make a right use of git in this case because I didn't create a new branch, I was working in the 'mainProducts' one. My tests were not working and I stashed the changes and saved a local copy, and now that I've checked it, is not a good version... I did this because I assumed that with CI the test would have been executed and I did not want to cause any trouble.
**Nevertheless, I've uploaded the only thing that I have . It's at [Testing](https://github.com/Arquisoft/dede_en1b/tree/Testing).**
 
In the only specific scenario that I have, I was trying to test that the information of the products was displayed on screen. 
I use 'memory router' because I needed to due to some error related to 'useLocation'. I'll be working on the tests this weekend again. I found some really interesting sources from where I hope I can learn how to do everything in the right way. Like: [Common mistakes with react-testing-library](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library), from where I found [Fixed the 'not wrapped in act' warning](https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning) and [Learning material testing library](https://testing-library.com/docs/learning/). I think I will need to make a mock implementation of the functions wrapped and I will search about that.

The error I'm most concerned of is those encountered due to functions that change the state of the component and are wrapped inside the same function that returns the component, like this one for example:
![imagen](https://user-images.githubusercontent.com/66498000/162260667-b8741e81-4f53-4d0b-803a-3aeb35657d94.png)

I can only prove I tried to work on this through screenshots of dates of modification and my browser history:
![imagen](https://user-images.githubusercontent.com/66498000/162258245-14aa1f05-65dd-4455-9c86-88507e487177.png)

![imagen](https://user-images.githubusercontent.com/66498000/162258780-9331d9d3-996f-454a-99b0-e37d3ce8a790.png)

![imagen](https://user-images.githubusercontent.com/66498000/162258862-da569c17-2f65-40fa-90bb-b3b17924464d.png)

![imagen](https://user-images.githubusercontent.com/66498000/162258919-18290614-44e7-41d5-9a88-39d3abab39ab.png)

**Comment by pglez82** [comment]
It is ok Sebas. The only thing, for this last month, try that your work is reflected in the repository. I know that you have worked hard but just remember that, what we evaluate is the work present in the repository. Not only code, but issues, code review, etc.

About the act in the tests. Maybe this resource is useful: https://github.com/mrdulin/react-act-examples/blob/master/sync.md
