### ISSUE TITLE
[Third delivery] Summary - Miguel contribution

### ISSUE THREAD

**Issue by UO258220** [Arquisoft/dede_en1b#123]
In this delivery, I was in charge of saving the completed orders to database on checkout:

- #85 
- #97 

I also helped reviewing some pull requests:

- #84 
- #92

**Comment by pglez82** [comment]
Hi Miguel,

I need links to the pull request(s) where you did the actual code for the save new orders functionality. Once you update this issue, send me and email so I can check the contributions that you have done.

Pablo

**Comment by UO258220** [comment]
Sorry. Should be there now
